ktor:
  application:
    modules:
      - fr.rage.lafie.ApplicationKt.module
  deployment:
    port: 8080
database:
  host: $DB_HOST
  username: $DB_USER
  password: $DB_PASSWORD
  engine: postgresql
  driver: org.postgresql.Driver
